parameters:
  - name: mavenPomFile
    default: pom.xml
  - name: options
    default: ' '
  - name: goals
    default: package
  - name: jdkDirectory
    default: ' '
  - name: javaHomeOption
    default: 'JDKVersion'
  - name: jdkVersionOption
    default: 'default'
  - name: mavenDirectory
    default: ' '
  - name: mavenVersionOption
    default: 'default'
  - name: mavenSetM2Home
    default: false
  - name: publishJUnitResults
    default: true
  - name: testResultsFiles
    default: '**/surefire-reports/TEST-*.xml'
stages:
- stage: Build
  jobs:
  - job: MavenBuild
    variables:
    - group: Artifactory_Variables
    steps:
    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        goals: ${{ parameters.goals }}   #goals: 'package' # Optional
        mavenPomFile: ${{ parameters.mavenPomFile }}  #mavenPomFile: 'pom.xml' 
        javaHomeOption: ${{ parameters.javaHomeOption }}  #javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
        jdkVersionOption: ${{ parameters.jdkVersionOption }} #jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
        jdkDirectory: ${{ parameters.jdkDirectory }}  #jdkDirectory: # Required when javaHomeOption == Path
        mavenDirectory: ${{ parameters.mavenDirectory }}  #mavenDirectory: # Required when mavenVersionOption == Path
        mavenVersionOption: ${{ parameters.mavenVersionOption }}  #mavenVersionOption: 'Default' # Options: default, path
        mavenSetM2Home: ${{ parameters.mavenSetM2Home }}  #mavenSetM2Home: false # Required when mavenVersionOption == Path
        options: ${{ parameters.options }}  #options: # Optional
        publishJUnitResults: ${{ parameters.publishJUnitResults }}  #publishJUnitResults: true 
        testResultsFiles: ${{ parameters.testResultsFiles }}  #testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
       Contents: "$(build_artifact_Path)"
       TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: $(PlneArtifact_Name)'
      inputs:
       ArtifactName: $(PlneArtifact_Name)
